config/routes.rb
Blissett::Application.routes.draw do

  resources :people do
    collection do
      post :import
      get :autocomplete
    end
  end

  
  resources :places
  resources :countries

  resources :clubs
  resources :seasons
  resources :levels
  resources :competitions
  
  resources :stints
  resources :roles

  resources :matches
  
  get "static_pages/home"
  get "static_pages/about"
  

  root 'static_pages#home'

end

app/models/club.rb
class Club < ActiveRecord::Base

  validates :name, presence: true

  belongs_to :place
  has_one :country, through: :place
  
end

app/models/competition.rb
class Competition < ActiveRecord::Base

  has_many :seasons
end

app/models/country.rb
class Country < ActiveRecord::Base

  validates :name, presence: true
  validates_uniqueness_of :name
  
  has_many :places
  has_many :clubs, through: :places
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :season

end

app/models/person.rb
class Person < ActiveRecord::Base
  # searchkick autocomplete: ['first_name']
  searchkick autocomplete: [:first_name, :last_name], text_start: [:full_name]

  validates :first_name, presence: true
  validates :last_name,  presence: true

  belongs_to :place
  has_one :country, through: :place
  
  has_many :stints

  def full_name
    return "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/models/place.rb
class Place < ActiveRecord::Base

  validates :name, presence: true
  
  has_many :clubs
  has_many :people
  
  belongs_to :country

end

app/models/role.rb
class Role < ActiveRecord::Base

  
end

app/models/season.rb
class Season < ActiveRecord::Base

  belongs_to :competition

  has_many :matches
end

app/models/stint.rb
class Stint < ActiveRecord::Base

  validates  :join_date,  presence: true
  validates  :leave_date, presence: true

  belongs_to  :person

  belongs_to  :club

  belongs_to  :role


end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.find(:all)
  end

  def new
    @club = Club.new
    @countries = Country.find(:all)
    # @places = Place.where(:country_id => "@countries")

  end

  def edit
    @club = Club.find(params[:id])
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      flash[:success] = "success"
      redirect_to @club
    else
      render 'new'
    end
  end

  def show
    @club = Club.find(params[:id])

    @people = Person.find(:all)

    @people = Person.where(:place_id => @places)

  end


  def destroy
  end

  def update
  end

  private

    def club_params
      params.require(:club).permit(:name, :badge_url, :place_id, :country_id, :colour_hex)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.find(:all)

    @competitions = Competition.find(:all)
    @levels = Level.find(:all)
    
  end

  def new
    @season = Season.new
    @countries = Country.find(:all)
    # @places = Place.where(:country_id => "@countries")

    @competitions = Competition.find(:all)
    @levels = Level.find(:all)

  end

  def edit
    @season = Season.find(params[:id])

    @competitions = Competition.find(:all)
    @levels = Level.find(:all)
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      flash[:success] = "success"
      redirect_to @season
    else
      render 'new'
    end
  end

  def update
    @season = Season.find(params[:id])
    if @season.update_attributes(season_params)
      flash[:success] = "success"
      redirect_to @season
    else
      flash[:error] = "error"
      render 'edit'
    end
  end


  def show
    @season = Season.find(params[:id])

    @matches = Match.where(:season_id => @season)



    @players_available = Stint.find(:all, :conditions => ["join_date <= ? AND leave_date >= ?", @season.year_begin, @season.year_end])


  end


  def destroy
  end


  private

    def season_params
      params.require(:season).permit(:year_begin, :year_end, :level_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def distance a, b
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 0.621371192      # Radius in miles

    dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
    dlat_rad = (b[0]-a[0]) * rad_per_deg

    lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math.asin(Math.sqrt(a))

    delta = rm * c # Delta in miles

    delta.round
  end

  def watford_coords
    [51.65648900083038, -0.3903200011700392]
  end
  
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper

  def places_array
    
    [
    @places.each do |place|
      return "#{place.lat}" , "#{place.lon}"
    end
    ]
  end

end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/places_helper.rb
module PlacesHelper

end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stints_helper.rb
module StintsHelper
end

app/views/seasons/edit.html.haml
%h1 Edit season

= form_for(@season) do |f|

  %fieldset

    = f.label :year_begin
    = f.select :year_begin, 1850..(Time.zone.now.year)

    %br 

    = f.label :year_end
    = f.select :year_end, 1850..(Time.zone.now.year)


  %fieldset

    = f.label :competition_id
    = f.collection_select :competition_id, @competitions, :id, :name

    = f.label :level_id
    = f.collection_select :level_id, @levels, :id, :tier

  %br

  = f.submit "Edit this season", class: "btn btn-large btn-primary"

app/views/seasons/index.html.haml
%h1 All seasons

%table
  %thead
    %tr
      %td id
      %td Season
      %td comp
      %td level

  - @seasons.each do |season|
    %tr
      %td 
        = season.id
      %td
        = link_to season.year_begin.to_s + "-" + season.year_end.to_s, season_path(season)
      %td
        = season.competition_id

      %td
        = season.level_id

        
%hr

        


= debug(@seasons)

app/views/seasons/new.html.haml
%h1 New season

= form_for(@season) do |f|

  / = f.label :name
  / = f.text_field :name


  / TODO: ONly show year field
  / TODO: Needs dropdown

  %br 

  = f.label :year_begin
  = f.select :year_begin, 1850..(Time.zone.now.year)

  %br 

  = f.label :year_end
  = f.select :year_end, 1850..(Time.zone.now.year)

  / = f.label :country_id
  / = f.collection_select :country_id, @countries, :id, :name

  %br

  = f.label :level_id
  = f.text_field :level_id

  %br

  = f.submit "Add a season", class: "btn btn-large btn-primary"

app/views/seasons/show.html.haml
%h1
  = @season.year_begin
  \-
  = @season.year_end
  season

%fieldset
  %b
    competing in
    ( Level
    = @season.level_id
    )



%br


%small
  %em
    = link_to "[New person]", new_person_path




%h3 players available:

%ul
- @players_available.each do |player|
  / = debug player
  - @player_name = Person.find(player.person_id).first_name + " " + Person.find(player.person_id).last_name
  %li
    
    / = link_to @player_name, person_path(player.person_id)
    = @player_name


%hr
%h3
  ADMIN: Declare who competed this season



%hr


%h2
  Players this season


%hr

%h2
  Matches this season

%table
  %tr
    %td Date
    %td Level
    %td Opposition
    %td Season
    %td Attendance
    %td is home?
    %td home_goals
    %td away_goals

  - @matches.each do |match|
    
    / TODO: Split by competition

    %tr
      %td
        = match.date
      %td
        = @season.level_id
      %td
        = Club.find(match.opposition_id).name
      %td
        = match.season_id
      %td
        = match.attendance
      %td
        = match.is_home
      %td
        = match.home_goals
      %td
        = match.away_goals


      / t.date :date
      / t.integer :competition_id
      / t.integer :opposition_id
      / t.integer :season_id
      
      / t.integer :attendance
      / t.boolean :is_home
      / t.integer :home_goals
      / t.integer :away_goals




= debug @season

app/views/seasons/update.html.haml
%h1 Update season