config/routes.rb
Blissett::Application.routes.draw do

  resources :people do
    collection do
      post :import
      get :autocomplete
    end
  end

  
  resources :places
  resources :countries

  resources :clubs
  resources :seasons
  resources :levels
  resources :competitions
  
  resources :stints
  resources :roles

  resources :matches
  
  get "static_pages/home"
  get "static_pages/about"
  

  root 'static_pages#home'

end

app/models/club.rb
class Club < ActiveRecord::Base

  validates :name, presence: true

  belongs_to :place
  has_one :country, through: :place
  
end

app/models/competition.rb
class Competition < ActiveRecord::Base

  has_many :seasons
end

app/models/country.rb
class Country < ActiveRecord::Base

  validates :name, presence: true
  validates_uniqueness_of :name
  
  has_many :places
  has_many :clubs, through: :places
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :season

end

app/models/person.rb
class Person < ActiveRecord::Base
  # searchkick autocomplete: ['first_name']
  searchkick autocomplete: [:first_name, :last_name], text_start: [:full_name]

  validates :first_name, presence: true
  validates :last_name,  presence: true

  belongs_to :place
  has_one :country, through: :place
  
  has_many :stints

  def full_name
    return "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/models/place.rb
class Place < ActiveRecord::Base

  validates :name, presence: true
  
  has_many :clubs
  has_many :people
  
  belongs_to :country

end

app/models/role.rb
class Role < ActiveRecord::Base

  
end

app/models/season.rb
class Season < ActiveRecord::Base

  belongs_to :competition

  has_many :matches
end

app/models/stint.rb
class Stint < ActiveRecord::Base

  validates  :join_date,  presence: true
  validates  :leave_date, presence: true

  belongs_to  :person

  belongs_to  :club

  belongs_to  :role


end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.find(:all)
  end

  def new
    @club = Club.new
    @countries = Country.find(:all)
    # @places = Place.where(:country_id => "@countries")

  end

  def edit
    @club = Club.find(params[:id])
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      flash[:success] = "success"
      redirect_to @club
    else
      render 'new'
    end
  end

  def show
    @club = Club.find(params[:id])

    @people = Person.find(:all)

    @people = Person.where(:place_id => @places)

  end


  def destroy
  end

  def update
  end

  private

    def club_params
      params.require(:club).permit(:name, :badge_url, :place_id, :country_id, :colour_hex)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def new
    @role = Role.new
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:success] = "success"
      redirect_to @role
    else
      render 'new'
    end
  end

  def show
    @role = Role.find(params[:id])
  end


  def update
  end

  def index
    @roles = Role.find(:all)
  end

  private

    def role_params
      params.require(:role).permit(:name)
    end

end

app/controllers/stints_controller.rb
class StintsController < ApplicationController
  def new
    @stint  = Stint.new
    @clubs  = Club.find(:all)
    @people = Person.find(:all)
    @roles  = Role.find(:all)
  end

  def edit
    @stint = Stint.find(params[:id])
    @clubs  = Club.find(:all)
    @people = Person.find(:all)
    @roles  = Role.find(:all)
  end

  def show
    @stint = Stint.find(params[:id])
    @club_sold_to = Club.find(@stint.sold_to) if @stint.sold_to

  end


  def create
    @stint = Stint.new(stint_params)
    if @stint.save
      flash[:success] = "success"
      redirect_to @stint
    else
      render 'new'
    end    
  end

  def destroy
  end

  def update
    @stint = Stint.find(params[:id])
    if @stint.update_attributes(stint_params)
      flash[:success] = "success"
      redirect_to @stint
    else
      flash[:error] = "error"
      render 'edit'
    end    
  end

  def index
    @stints = Stint.find(:all)
    @clubs = Club.find(:all)
    @roles = Role.find(:all)

  end

  private

    def stint_params
      params.require(:stint).permit(:person_id, :role_id, :join_date, :leave_date, :from, :bought_fee, :sold_to, :sold_fee, :is_permanent, :is_one_of_our_own)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def distance a, b
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 0.621371192      # Radius in miles

    dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
    dlat_rad = (b[0]-a[0]) * rad_per_deg

    lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math.asin(Math.sqrt(a))

    delta = rm * c # Delta in miles

    delta.round
  end

  def watford_coords
    [51.65648900083038, -0.3903200011700392]
  end
  
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper

  def places_array
    
    [
    @places.each do |place|
      return "#{place.lat}" , "#{place.lon}"
    end
    ]
  end

end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/places_helper.rb
module PlacesHelper

end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stints_helper.rb
module StintsHelper
end

app/views/stints/create.html.haml
%h1 Stints#create
%p Find me in app/views/stints/create.html.haml

app/views/stints/destroy.html.haml
%h1 Stints#destroy
%p Find me in app/views/stints/destroy.html.haml

app/views/stints/edit.html.haml
%h1 Stints#edit
%p Find me in app/views/stints/edit.html.haml

= form_for(@stint) do |f|

  = f.label :person_id
  = f.collection_select :person_id, @people, :id, :last_name  

  = f.label :role_id
  = f.collection_select :role_id, @roles, :id, :name

  %br 

  = f.label :join_date
  = f.select :join_date, 1950..(Time.zone.now.year)

  %br 

  = f.label :leave_date
  = f.select :leave_date, 1950..(Time.zone.now.year)

  %br 

  %fieldset

    = f.label :is_permanent, "Permanent signing?"
    = f.check_box :is_permanent, {checked: true}

    %br

    = f.label :is_one_of_our_own
    = f.check_box :is_one_of_our_own

    or 
    
    = f.label :from, "from"
    = f.collection_select :from, @clubs, :id, :name, include_blank: true

    = f.label :bought_fee, "fee?"
    = f.text_field :bought_fee

  
  %fieldset

    = f.label :sold_to
    = f.collection_select :sold_to, @clubs, :id, :name, include_blank: true 

    = f.label :sold_fee
    = f.text_field :sold_fee


  %br

  = f.submit "Edit a stint", class: "btn btn-large btn-primary"

app/views/stints/index.html.haml
%h1 All stints

%table
  %thead
    %tr
      %td 
      %td Person
      %td Role
      %td Joined
      %td Left
      %td From
      %td Fee
      %td To
      %td Fee

  - @stints.each do |stint|
    %tr
      %td 
        = link_to "edit", edit_stint_path(stint)
        ,
        = link_to "show", stint_path(stint)
      %td
        = link_to stint.person.first_name + " " + stint.person.last_name, stint.person       
      %td 
        = link_to @roles[stint.role_id.to_i - 1].name, role_path(@roles[ stint.role_id.to_i - 1])
      %td
        = stint.join_date
      %td
        = stint.leave_date
      %td
        - if stint.from
          = link_to @clubs[stint.from.to_i - 1].name, club_path(@clubs[ stint.from.to_i - 1])        
      %td
        = number_to_currency(stint.bought_fee, :precision => 0, :unit => "&pound;")
      %td
        = link_to @clubs[ stint.sold_to - 1].name, club_path(@clubs[ stint.sold_to - 1]) if stint.sold_to

        / = @clubs[stint.sold_to].name

      %td
        = number_to_currency(stint.sold_fee, :precision => 0, :unit => "&pound;")

%hr

= debug(@stints)

app/views/stints/new.html.haml
%h1 Stints#new

= form_for(@stint) do |f|

  = f.label :person_id
  = f.collection_select :person_id, @people, :id, :last_name  

  = f.label :role_id
  = f.collection_select :role_id, @roles, :id, :name

  %br 

  = f.label :join_date
  = f.select :join_date, 1950..(Time.zone.now.year)

  %br 

  = f.label :leave_date
  = f.select :leave_date, 1950..(Time.zone.now.year)

  %br 

  %fieldset

    = f.label :is_permanent, "Permanent signing?"
    = f.check_box :is_permanent, {checked: true}

    %br

    = f.label :is_one_of_our_own
    = f.check_box :is_one_of_our_own

    or 

    = f.label :from, "from"
    = f.collection_select :from, @clubs, :id, :name, include_blank: true

    = f.label :bought_fee, "fee?"
    = f.text_field :bought_fee

  
  %fieldset

    = f.label :sold_to
    = f.collection_select :sold_to, @clubs, :id, :name, include_blank: true 

    = f.label :sold_fee
    = f.text_field :sold_fee


  %br

  = f.submit "Add a stint", class: "btn btn-large btn-primary"

app/views/stints/show.html.haml
%h1

  Stint as a
  
  = link_to @stint.role.name, @stint.role

  for

  = link_to @stint.person.first_name + " " + @stint.person.last_name, @stint.person
  
%fieldset

  (

  = @stint.join_date

  - if @stint.join_date != @stint.leave_date
    \-

    = @stint.leave_date
  )

  %br
  
  - if @club_sold_to
    Sold to 
    = link_to @club_sold_to.name, club_path(@club_sold_to)

    - if @stint.sold_fee
      for
      = number_to_currency(@stint.sold_fee, :precision => 0, :unit => "&pound;")


  - if !@stint.is_permanent?
    on loan


%hr

= debug @stint.person.stints

/= debug @stint

app/views/stints/update.html.haml
%h1 Stints#update
%p Find me in app/views/stints/update.html.haml