config/routes.rb
Blissett::Application.routes.draw do

  resources :people do
    collection do
      post :import
      get :autocomplete
    end
  end

  
  resources :places
  resources :countries

  resources :clubs
  resources :seasons
  resources :levels
  resources :competitions
  
  resources :stints
  resources :roles

  resources :matches
  
  get "static_pages/home"
  get "static_pages/about"
  

  root 'static_pages#home'

end

app/models/club.rb
class Club < ActiveRecord::Base

  validates :name, presence: true

  belongs_to :place
  has_one :country, through: :place
  
end

app/models/competition.rb
class Competition < ActiveRecord::Base

  has_many :seasons
end

app/models/country.rb
class Country < ActiveRecord::Base

  validates :name, presence: true
  validates_uniqueness_of :name
  
  has_many :places
  has_many :clubs, through: :places
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :season

end

app/models/person.rb
class Person < ActiveRecord::Base
  # searchkick autocomplete: ['first_name']
  searchkick autocomplete: [:first_name, :last_name], text_start: [:full_name]

  validates :first_name, presence: true
  validates :last_name,  presence: true

  belongs_to :place
  has_one :country, through: :place
  
  has_many :stints

  def full_name
    return "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/models/place.rb
class Place < ActiveRecord::Base

  validates :name, presence: true
  
  has_many :clubs
  has_many :people
  
  belongs_to :country

end

app/models/role.rb
class Role < ActiveRecord::Base

  
end

app/models/season.rb
class Season < ActiveRecord::Base

  belongs_to :competition

  has_many :matches
end

app/models/stint.rb
class Stint < ActiveRecord::Base

  validates  :join_date,  presence: true
  validates  :leave_date, presence: true

  belongs_to  :person

  belongs_to  :club

  belongs_to  :role


end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.find(:all)
  end

  def new
    @club = Club.new
    @countries = Country.find(:all)
    # @places = Place.where(:country_id => "@countries")

  end

  def edit
    @club = Club.find(params[:id])
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      flash[:success] = "success"
      redirect_to @club
    else
      render 'new'
    end
  end

  def show
    @club = Club.find(params[:id])

    @people = Person.find(:all)

    @people = Person.where(:place_id => @places)

  end


  def destroy
  end

  def update
  end

  private

    def club_params
      params.require(:club).permit(:name, :badge_url, :place_id, :country_id, :colour_hex)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    if params[:query].present?
      @results = Person.search(params[:query], page: params[:page])
    else
      @results = Person.all.page params[:page]
    end
    
    @people = Person.find(:all, :order => :last_name)

  end

  def new
    @person = Person.new
    @places = Place.find(:all, :order => :name)
    @countries = Country.find(:all, :order => :name)
  end

  def edit
    @person = Person.find(params[:id])
    @places = Place.find(:all, :order => :name)
    @countries = Country.find(:all, :order => :name)

  end


  def show
    @person = Person.find(params[:id])
    @place  = Place.find(@person.place_id) if @person.place
    @country = @place.country if @person.country
    @stints = @person.stints
    
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:success] = "success"
      redirect_to @person
    else
      flash[:error] = "error"
      render 'new'
    end
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      flash[:success] = "success"
      redirect_to @person
    else
      flash[:error] = "error"
      render 'edit'
    end
  end

  def autocomplete
    # render json: Person.search(params[:query], partial: true, autocomplete: true, limit: 10).map(&:first_name)

    
    render json: Person.search(params[:query], partial: true, autocomplete: true, limit: 10).map(&:full_name)


  end


  

  private

    def person_params
      params.require(:person).permit(:first_name, :middle_name, :last_name, :date_of_birth, :place_id, :bio, :photo_url, :photo_caption, :watford_legends_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def distance a, b
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 0.621371192      # Radius in miles

    dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
    dlat_rad = (b[0]-a[0]) * rad_per_deg

    lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math.asin(Math.sqrt(a))

    delta = rm * c # Delta in miles

    delta.round
  end

  def watford_coords
    [51.65648900083038, -0.3903200011700392]
  end
  
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper

  def places_array
    
    [
    @places.each do |place|
      return "#{place.lat}" , "#{place.lon}"
    end
    ]
  end

end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/places_helper.rb
module PlacesHelper

end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stints_helper.rb
module StintsHelper
end

app/views/people/_form.html.haml
%fieldset
  = f.label :first_name 
  = f.text_field :first_name

  %br

  = f.label :middle_name
  = f.text_field :middle_name

  %br

  = f.label :last_name
  = f.text_field :last_name

%fieldset
  = f.label :photo_url
  = f.text_field :photo_url

  %br

  = f.label :photo_caption
  = f.text_field :photo_caption

%fieldset
  = f.label :date_of_birth
  = f.date_select :date_of_birth, start_year: 1850, include_blank: true

  %br
  = f.label :place_id
  = f.grouped_collection_select :place_id, @countries, :places, :name, :id, :name,  include_blank: true

%br

= f.label :watford_legends_url, "watford legends url?"
= f.text_field :watford_legends_url


%br

= f.label :bio
= f.text_area :bio   

app/views/people/edit.html.erb
<h1>Edit person</h1>

<%= form_for(@person) do |f| %>

  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <br>

    <%= f.submit "Edit " + @person.first_name + " " + @person.last_name, class: "btn btn-large btn-primary" %>
  </fieldset>

<% end %>

app/views/people/index.html.haml
%h1 All people

%hr

= form_tag people_path, class: "form-inline", method: :get do
  .input-group.input-group-lg
    - if params[:query].present?
      .input-group-btn
        = link_to "clear", people_path, class: "btn btn-default"
    = text_field_tag :query, params[:query], class: "form-control", id: "person_search", autocomplete: "off"
    .input-group-btn
      = submit_tag "Search", class: "btn btn-primary"


%table{border: "1"}
  %thead
    %tr
      %td id
      %td Name

      %td Stint(s)

      %td birthday

      %td From
      %td Bio

      %td Height
      %td photo
      %td caption
      %td watford legends url

  - @people.each do |person|

    
    %tr
      %td 
        = person.id
      %td 
        = link_to "" + person.full_name, person
      %td
        - person.stints.each do |stint| 
          %p
            = link_to "link", stint_path(stint)
            = stint.join_date
            - if stint.join_date != stint.leave_date
              to 
              = stint.leave_date

      %td
        = person.date_of_birth
      %td
        = person.place.name if person.place
      %td
        = person.bio
      %td
        = person.height
      %td
        = person.photo_url
      %td
        = person.photo_caption
      %td
        - if person.watford_legends_url != ''
          = link_to "Watford Legends", person.watford_legends_url

        / person.first_name + " " + person.last_name + " article at Watford Legends"


%hr

= debug(@people)

app/views/people/new.html.erb
<h1>New person</h1>

<%= form_for(@person) do |f| %>

  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <br>
    <%= f.submit "Add a person", class: "btn btn-large btn-primary" %>
  </fieldset>

<% end %>

app/views/people/show.html.haml
/ TODO: Move CSS

:css
  #map { width: 200px; height: 200px; }

%h1
  = @person.first_name
  = @person.last_name

%fieldset

  %b DOB
  = @person.date_of_birth
  %br
  %b Place of birth
  
  - if @place
    = @place.name
  - else
    No place given
  ,

  - if @country
    = @country.name
  - else
    No country given

%br

- if !@person.photo_url.empty?
  %aside
    = image_tag @person.photo_url, {height: 100}
    - if @person.photo_caption
      %cite= @person.photo_caption

/ TODO: Logic if there are middle names @person.middle_name etc..



- if @stints && !@stints.empty?
  %hr
  %h2 Stints
  - @stints.each do |stint|
    %fieldset
      %h3

        = stint.join_date
        \-
        = stint.leave_date
        as 
        = stint.role.name
        - if !stint.is_permanent
          on loan

        = stint.bought_fee if stint.bought_fee
        = stint.sold_fee if stint.sold_fee

      %br
      = stint.from if stint.from
      %br
      = stint.sold_to if stint.sold_to

  %hr




%br
/ TODO: Map
- if @place && @place.lat && @country && @country.name != "England"
  = distance watford_coords,[@place.lat, @place.lon]
  miles away from Vicarage Road

  = map(:center => {:latlng => [@place.lat, @place.lon], :zoom => 6 }, :markers => [{ :latlng => [@place.lat, @place.lon] }])

%br

- if !@person.watford_legends_url.blank?
  = link_to "" + @person.last_name + " legends article", @person.watford_legends_url

%hr/
- if !@person.bio.blank?
  %h2 Bio
  %div
    = @person.bio

= debug @person